/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MiPlanRouteImport } from './routes/mi-plan'
import { Route as PacientePacienteIdRouteImport } from './routes/paciente.$pacienteId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MiPlanRoute = MiPlanRouteImport.update({
  id: '/mi-plan',
  path: '/mi-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientePacienteIdRoute = PacientePacienteIdRouteImport.update({
  id: '/paciente/$pacienteId',
  path: '/paciente/$pacienteId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mi-plan': typeof MiPlanRoute
  '/paciente/$pacienteId': typeof PacientePacienteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mi-plan': typeof MiPlanRoute
  '/paciente/$pacienteId': typeof PacientePacienteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mi-plan': typeof MiPlanRoute
  '/paciente/$pacienteId': typeof PacientePacienteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mi-plan' | '/paciente/$pacienteId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mi-plan' | '/paciente/$pacienteId'
  id: '__root__' | '/' | '/mi-plan' | '/paciente/$pacienteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MiPlanRoute: typeof MiPlanRoute
  PacientePacienteIdRoute: typeof PacientePacienteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-plan': {
      id: '/mi-plan'
      path: '/mi-plan'
      fullPath: '/mi-plan'
      preLoaderRoute: typeof MiPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paciente/$pacienteId': {
      id: '/paciente/$pacienteId'
      path: '/paciente/$pacienteId'
      fullPath: '/paciente/$pacienteId'
      preLoaderRoute: typeof PacientePacienteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MiPlanRoute: MiPlanRoute,
  PacientePacienteIdRoute: PacientePacienteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
